[project]
name = "implementations"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "cvxpy>=1.7.3",
    "numpy>=2.3.4",
    "scipy>=1.16.2",
    "scipy-stubs==1.16.2.4",
]
